<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PokeTokenBar</AssemblyName>
    <RootNamespace>PokeTokenBar.Ui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\PokeTokenBar.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\pokeball.ico" Link="Assets\pokeball.ico" />
  </ItemGroup>

</Project>
